---
repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-vet
        always_run: true
      - id: go-build
        always_run: true
      - id: go-mod-tidy
        always_run: true
