---
name: tinykmetrics CI

on:
  release:
    types: [created]

env:
  IMAGE_NAME: tinykmetrics

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/stenstromen/${{ env.IMAGE_NAME }}:latest
            ghcr.io/stenstromen/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  flux-update:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      VERSIONTAG: ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout flux repository
        uses: actions/checkout@v4
        with:
          repository: stenstromen/flux
          token: ${{ secrets.KUBE_GITHUB_TOKEN }}
          path: flux-repo
          fetch-depth: 0

      - name: Fetch repository content
        run: |
          cd flux-repo
          git fetch origin
          git checkout main

      - name: Update Deployment image tag
        run: |
          DEPLOYMENT_FILE="flux-repo/apps/stinky/tinykmetrics/tinykmetrics_deployment.yaml"
          OLD_IMAGE=$(grep "image:" "$DEPLOYMENT_FILE" | awk '{print $2}')
          NEW_IMAGE="ghcr.io/stenstromen/tinykmetrics:$VERSIONTAG"

          # Update the image tag
          sed -i "s|image:.*|image: $NEW_IMAGE|" "$DEPLOYMENT_FILE"

          # Create commit message
          echo "Update image: $OLD_IMAGE -> $NEW_IMAGE" > commit_message.txt

      - name: Commit and Push Flux Deployment Update
        run: |
          cd flux-repo
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add apps/stinky/tinykmetrics/tinykmetrics_deployment.yaml
          git commit -F ../commit_message.txt
          git push
